theme: 'hugo-theme-readable-cb'
title: 'U Tulsa ARC'

languages:
  en:
    languageName: English
    menu:
      main:
      - name: Join Now
        url: /join
        weight: 10
      - name: Home
        url: /
        weight: 1

frontmatter:
  lastmod:
  - lastmod
  - date
  - publishDate
